# Generated by Django 4.0.3 on 2022-04-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_opportunity_primary_contact_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='office_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
