# Generated by Django 4.0.4 on 2022-05-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_employee_manager_employee_office_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('L', 'Lead'), ('O', 'Opportunity'), ('C', 'Active Customer'), ('FC', 'Former Customer'), ('I', 'Inactive')], default='N', max_length=2),
        ),
    ]
