# Generated by Django 4.0.4 on 2022-05-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_opportunity_value_alter_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
